name: Say Hello
on: push
jobs:
  job1:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: python hello.py

  job2:
    name: Build
    needs: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: action/upload-artifact@v2
        with:
          name: hello
          path: .
